"""add source column, metric_snapshot, facebook and instagram stats tables

Revision ID: 067d847241d2
Revises: a1b2c3d4e5f6
Create Date: 2026-02-03 16:55:34.632731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067d847241d2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin_org_stats', 'follower_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('linkedin_org_stats', 'page_views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('posts', sa.Column('source', sa.String(length=20), server_default='webhook', nullable=False))
    op.create_unique_constraint('uix_posts_platform_provider', 'posts', ['platform', 'provider_post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_posts_platform_provider', 'posts', type_='unique')
    op.drop_column('posts', 'source')
    op.alter_column('linkedin_org_stats', 'page_views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('linkedin_org_stats', 'follower_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
