"""add multi-tenant models

Revision ID: 7c596193eb7d
Revises: add_diarized_transcript
Create Date: 2026-01-28 20:09:31.842688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c596193eb7d'
down_revision: Union[str, None] = 'add_diarized_transcript'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_slug'), 'clients', ['slug'], unique=True)
    op.create_table('kols',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_table('client_users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='clientrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_users_client_id'), 'client_users', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_users_user_id'), 'client_users', ['user_id'], unique=False)
    op.create_table('kol_groups',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kol_groups_project_id'), 'kol_groups', ['project_id'], unique=False)
    op.create_table('kol_group_members',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kol_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kol_group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kol_group_id'], ['kol_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kol_id'], ['kols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kol_group_members_kol_group_id'), 'kol_group_members', ['kol_group_id'], unique=False)
    op.create_index(op.f('ix_kol_group_members_kol_id'), 'kol_group_members', ['kol_id'], unique=False)
    op.add_column('shoots', sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('shoots', sa.Column('kol_group_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_shoots_kol_group_id'), 'shoots', ['kol_group_id'], unique=False)
    op.create_index(op.f('ix_shoots_project_id'), 'shoots', ['project_id'], unique=False)
    op.create_foreign_key(None, 'shoots', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'shoots', 'kol_groups', ['kol_group_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('default_client_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'users', 'clients', ['default_client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_client_id')
    op.drop_constraint(None, 'shoots', type_='foreignkey')
    op.drop_constraint(None, 'shoots', type_='foreignkey')
    op.drop_index(op.f('ix_shoots_project_id'), table_name='shoots')
    op.drop_index(op.f('ix_shoots_kol_group_id'), table_name='shoots')
    op.drop_column('shoots', 'kol_group_id')
    op.drop_column('shoots', 'project_id')
    op.drop_index(op.f('ix_kol_group_members_kol_id'), table_name='kol_group_members')
    op.drop_index(op.f('ix_kol_group_members_kol_group_id'), table_name='kol_group_members')
    op.drop_table('kol_group_members')
    op.drop_index(op.f('ix_kol_groups_project_id'), table_name='kol_groups')
    op.drop_table('kol_groups')
    op.drop_index(op.f('ix_client_users_user_id'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_client_id'), table_name='client_users')
    op.drop_table('client_users')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('kols')
    op.drop_index(op.f('ix_clients_slug'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
