"""add metadata fields to kol_groups and clips

Revision ID: c4665648bc07
Revises: 7c596193eb7d
Create Date: 2026-01-28 20:17:42.514166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4665648bc07'
down_revision: Union[str, None] = '7c596193eb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    content_type_enum = sa.Enum('FULL_PODCAST', 'CLIP', name='content_type')
    media_type_enum = sa.Enum('VIDEO', 'AUDIO', name='media_type')
    content_type_enum.create(op.get_bind(), checkfirst=True)
    media_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('clips', sa.Column('shoot_id', sa.String(length=255), nullable=True))
    op.add_column('clips', sa.Column('clip_number', sa.Integer(), nullable=True))
    op.add_column('clips', sa.Column('content_type', content_type_enum, nullable=True))
    op.add_column('clips', sa.Column('media_type', media_type_enum, nullable=True))
    op.add_column('clips', sa.Column('thumbnail_path', sa.String(length=1000), nullable=True))
    op.add_column('clips', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_clips_shoot_id'), 'clips', ['shoot_id'], unique=False)
    op.create_foreign_key(None, 'clips', 'shoots', ['shoot_id'], ['id'], ondelete='SET NULL')
    op.add_column('kol_groups', sa.Column('video_count', sa.Integer(), nullable=True))
    op.add_column('kol_groups', sa.Column('publish_day', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kol_groups', 'publish_day')
    op.drop_column('kol_groups', 'video_count')
    op.drop_constraint(None, 'clips', type_='foreignkey')
    op.drop_index(op.f('ix_clips_shoot_id'), table_name='clips')
    op.drop_column('clips', 'duration_seconds')
    op.drop_column('clips', 'thumbnail_path')
    op.drop_column('clips', 'media_type')
    op.drop_column('clips', 'content_type')
    op.drop_column('clips', 'clip_number')
    op.drop_column('clips', 'shoot_id')

    # Drop enum types
    sa.Enum(name='content_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='media_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
